Update oocodegen.map_type to use optional slot.required
linkml/linkml pull request #1024
Opened 2022-10-20 16:57 UTC by julesjacobsen

Update javagen.py to check slot.required before deciding to use a primitive or wrapper type for int, float, double.

2022-10-20 17:38 UTC, julesjacobsen commented on linkml/generators/oocodegen.py
> +                # TODO:
Needs wiring-up here! Not sure how the existing types need to be retained/overridden.

2022-10-20 17:39 UTC, julesjacobsen commented
Still a bit to do - requires wiring-up of default_value_for_type in oocodegen (see comment in files changed)
pydanticgen needs to implement  default_value_for_type  too?

2022-10-26 16:28 UTC, julesjacobsen commented
This has been updated to add in new Java functionality to create a Java Interface for mixin types and add in the description to the generated classes e.g.

```yaml
classes:
  annotatable:
    description: mixin for classes that support annotations
    mixin: true
    slots:
      - annotations

  annotation:
    description: a tag/value pair with the semantics of OWL Annotation
    is_a: extension
    mixins:
      - annotatable
    slots:
      - annotations
```

produces

```java

/**
 * mixin for classes that support annotations
 */
public interface Annotatable {

    public List<Annotation> annotations();
}

/**
 * a tag/value pair with the semantics of OWL Annotation
 */
public record Annotation(List<Annotation> annotations, String extensionTag, String extensionValue, List<Extension> extensions) implements Annotatable {}
```

2022-10-26 18:01 UTC, cmungall commented
still to address:

```
Traceback (most recent call last):
  File "/home/runner/work/linkml/linkml/tests/test_generators/test_javagen.py", line 44, in test_javagen_classes
    gen.serialize(directory=JAVA_DIR)
  File "/home/runner/work/linkml/linkml/linkml/generators/javagen.py", line 126, in serialize
    code = template_interface.render(
UnboundLocalError: local variable 'template_interface' referenced before assignment
```

2022-10-26 18:34 UTC, kevinschaper approved these changes

2022-10-26 19:03 UTC, cmungall requested changes
can merge as soon as tests pass..

2022-10-28 02:24 UTC, merged