Could not determine join condition between parent/child tables
linkml/linkml pull request #1105
Opened 2022-11-11 19:55 UTC by turbomam

only test_do_dump_sqlite fails

#1104 

`poetry run pytest tests/test_data/test_issue_1104.py`

2022-11-14 19:55 UTC, cmungall requested changes
Now works. Before merging can we move files to conform to https://linkml.io/linkml/contributing/contributing.html @sujaypatil96 can help

2022-11-15 19:01 UTC, turbomam commented
Uploading of the code coverage report is failing under ubuntu-latest, Python 3.9:

```
Run codecov/codecov-action@v3.1.0
==> linux OS detected
https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
==> SHASUM file signed by key id 806bb28aed779869
==> Uploader SHASUM verified (20f9c9d78483fce977b6cc39e231a734a23bcd36f4d536bb7355222fb88d02bc  codecov)
==> Running version latest
==> Running version v0.3.2
/home/runner/work/_actions/codecov/codecov-action/v3.1.0/dist/codecov -n codecov-results-ubuntu-latest-3.9 -Q github-action-3.1.0 -Z -f coverage.xml -C 1c881b25a7e7398385b058797d4501f3d9d57e7f
[2022-[11](https://github.com/linkml/linkml/actions/runs/3465165635/jobs/5787575699#step:11:12)-14T21:26:52.104Z] ['info'] 
     _____          _
    / ____|        | |
   | |     ___   __| | ___  ___ _____   __
   | |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
   | |___| (_) | (_| |  __/ (_| (_) \ V /
    \_____\___/ \__,_|\___|\___\___/ \_/

  Codecov report uploader 0.3.2
[2022-11-14T21:26:52.1[12](https://github.com/linkml/linkml/actions/runs/3465165635/jobs/5787575699#step:11:13)Z] ['info'] => Project root located at: /home/runner/work/linkml/linkml
[2022-11-[14](https://github.com/linkml/linkml/actions/runs/3465165635/jobs/5787575699#step:11:15)T21:26:52.112Z] ['info'] ->  Token found by environment variables
[2022-11-14T21:26:52.123Z] ['info'] Searching for coverage files...
[2022-11-14T21:26:52.390Z] ['info'] => Found 1 possible coverage files:
  coverage.xml
[2022-11-14T21:26:52.390Z] ['info'] Processing /home/runner/work/linkml/linkml/coverage.xml...
[2022-11-14T21:26:52.403Z] ['info'] Using manual override from args.
[2022-11-14T21:26:52.403Z] ['info'] Detected GitHub Actions as the CI provider.
[2022-11-14T21:26:52.404Z] ['info'] Pinging Codecov: https://codecov.io/upload/v4?package=github-action-3.1.0-uploader-0.3.2&token=*******&branch=issue-1104-bad-sqldb-dump-join&build=3465[16](https://github.com/linkml/linkml/actions/runs/3465165635/jobs/5787575699#step:11:17)5635&build_url=https%3A%2F%2Fgithub.com%2Flinkml%2Flinkml%2Factions%2Fruns%2F3465165635&commit=1c881b25a7e7398385b058797d4501f3d9d57e7f&job=Build+and+test+linkml&pr=1105&service=github-actions&slug=linkml%2Flinkml&name=codecov-results-ubuntu-latest-3.9&tag=&flags=&parent=
[[20](https://github.com/linkml/linkml/actions/runs/3465165635/jobs/5787575699#step:11:21)22-11-14T[21](https://github.com/linkml/linkml/actions/runs/3465165635/jobs/5787575699#step:11:22):26:52.643Z] ['error'] There was an error running the uploader: Error uploading to https://codecov.io: Error: There was an error fetching the storage URL during POST: 503 - upstream connect error or disconnect/reset before headers. reset reason: connection failure
Error: Codecov: Failed to properly upload: The process '/home/runner/work/_actions/codecov/codecov-action/v3.1.0/dist/codecov' failed with exit code [25](https://github.com/linkml/linkml/actions/runs/3465165635/jobs/5787575699#step:11:26)5
```

2022-11-16 16:22 UTC, cmungall commented
@turbomam - looks like a temporary glitch?

2022-11-16 16:23 UTC, cmungall approved these changes

2022-11-16 19:01 UTC, merged