feat(shacl): improve type generation
linkml/linkml pull request #1300
Opened 2023-02-20 22:27 UTC by noelmcloughlin

This PR improves shaclgen.py by adding nodeKind and datatype for Linkml types (fixes https://github.com/linkml/linkml/issues/1299)

Here is example output I generated from this PR where linkml type has nodeKind and datatype correctly generated.

```
sh:property [ sh:datatype "xsd:anyURI" ;
            sh:description "Specifies a reference to a resource outside of the UCO." ;
            sh:nodeKind sh:IRI ;
            sh:order 3 ;
            sh:path core:externalReference ],
        [ sh:datatype "xsd:string" ;
            sh:description "The name of a particular concept characterization." ;
            sh:maxCount 1 ;
            sh:nodeKind sh:Literal ;
            sh:order 6 ;
            sh:path core:name ]
```

2023-02-21 19:22 UTC, cmungall commented
Thanks for taking this on!

I believe sh:datatype should only be used for literals https://www.w3.org/TR/shacl/#validator-DatatypeConstraintComponent

ideally the unit tests would use pyshacl to test that validation works as expected but let's hold off on adding that as a dependency for now. For now we can just check the resulting shacl triples map as extended, and we can do an out of band test to ensure the shacl validates as expected

2023-02-21 23:13 UTC, noelmcloughlin commented
Thanks @cmungall  Good point - we should pair datatype with Literals only.

I am checking my linkml generated shacl against a control rdfs+shacl file someone else created which only declares sh:IRI and sh:Literal nodeKinds. However my PR is naive.

From docs: "_The values of sh:nodeKind in a shape are one of the following six instances of the class sh:NodeKind: sh:BlankNode, sh:IRI, sh:Literal sh:BlankNodeOrIRI, sh:BlankNodeOrLiteral and sh:IRIOrLiteral._ "

Is there a way calculate correct nodeKind from value of  `str(Literal(rt.uri))` ?

2023-02-22 04:11 UTC, cmungall commented
If the range is a type, it’s a literal

If the range is a class with an identifier, iri

Class with no identifier, blank

Enums:

If all PVs have a meaning, iri
If none have meaning, literal
Otherwise iriorliteral

On Tue, Feb 21, 2023 at 3:13 PM N ***@***.***> wrote:

> Thanks @cmungall <https://github.com/cmungall> Good point - we should
> pair datatype with Literals only.
>
> I am checking my linkml generated shacl against a control rdfs+shacl file
> someone else created which only declares sh:IRI and sh:Literal nodeKinds.
> However my PR is naive.
>
> From docs: "*The values of sh:nodeKind in a shape are one of the
> following six instances of the class sh:NodeKind: sh:BlankNode, sh:IRI,
> sh:Literal sh:BlankNodeOrIRI, sh:BlankNodeOrLiteral and sh:IRIOrLiteral.*
> "
>
> Is there a way calculate correct nodeKind from value of
> str(Literal(rt.uri)) ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/linkml/linkml/pull/1300#issuecomment-1439214566>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAMMOJWXGLQSECS3KXYELDWYVD2PANCNFSM6AAAAAAVCK27CA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-15 23:58 UTC, cmungall requested changes

2023-03-15 23:58 UTC, cmungall commented on linkml/generators/shaclgen.py
> +                        prop_pv(SH.datatype, Literal(rt.uri))
I don't think this is right - even though the value of sh:datatype is used for validating literals, it is not itself a literal

See:

https://www.w3.org/TR/shacl/#DatatypeConstraintComponent

example:

```turtle
sh:property [
		sh:path ex:age ;
		sh:datatype xsd:integer ;
	] .
```

2024-02-15 22:06 UTC, nlharris commented
Looks like this still has changes requested.

2025-03-21 15:16 UTC, amc-corey-cox commented
It looks like this may have been closed with https://github.com/linkml/linkml/pull/2102 and this PR has been idle for a while. I'm going to close this for now. If you are still working on this you are welcome to re-open the PR and make updates so we can resolve the issue.

2025-03-21 15:16 UTC, closed without merging