Make materialization (attributes and patterns) default behaviour in `gen-linkml`
linkml/linkml pull request #2341
Opened 2024-10-01 19:21 UTC by sujaypatil96

This PR seeks to make materialization of both induced slots (as attributes) and structured patterns (as patterns) universal/true by default.

There are two optional arguments called `--materialize-attributes/no-materialize-attributes` and `materialize-patterns/no-materialize-patterns` which we are combining into a single optional argument called `--materialize/no-materialize`.

Let me know if you think I need to add any `CliRunner` tests to test the CLI option. If not, this is ready for review.

2024-10-01 19:58 UTC, sierra-moxon approved these changes

2024-10-03 14:29 UTC, turbomam reviewed
I don't feel strongly about the default state of the materialization option(s), but I do I prefer keeping the attribute and structured pattern separate. The schema a file that NMDC people and software interact with the most is a merged and pattern materialized version. I really don't want to start explaining attributes to the users and modify software to access attributes instead of slots.

But I won't object to this if somebody can help me come up with a plan for taking more of an attribute-first view of the schema.

2024-10-04 20:13 UTC, cmungall requested changes
rather than remove options, add an uber-option `--materialize` that sets all `--materialize-X` options.

2024-11-01 20:16 UTC, sierra-moxon approved these changes

2024-11-01 20:25 UTC, cmungall approved these changes

2024-11-01 20:25 UTC, merged