Add version flag
linkml/linkml pull request #434
Opened 2021-10-23 09:57 UTC by rosdyana

Solve issue #378

2021-11-02 22:55 UTC, sujaypatil96 commented
Thank you for clarifying that @rosdyana. I had a couple of other comments though.

2021-11-02 22:58 UTC, sujaypatil96 requested changes
Would you be able to resolve these two comments @rosdyana? I think we should be good to merge it right after.

2021-11-02 22:58 UTC, sujaypatil96 commented on setup.py
> +version = versioneer.get_version()
You're getting the version here, but not passing it to the `setup()`. From the `pandas` repo that you referenced, here is the [line](https://github.com/pandas-dev/pandas/blob/master/setup.py#L649) I'm referring to.

2021-11-02 22:58 UTC, sujaypatil96 commented on setup.py
> +cmdclass = versioneer.get_cmdclass()
Similar to `version`, you're not passing `cmdclass` to `setup()` either. Here is the [line](https://github.com/pandas-dev/pandas/blob/master/setup.py#L651) from pandas.

2021-11-03 03:52 UTC, rosdyana commented
@sujaypatil96 Sure, I just pushed a new commit to resolve that issue, thanks!

2021-11-03 21:36 UTC, sujaypatil96 approved these changes
Thank you @rosdyana. I think this PR is good to be merged.🚀

2021-11-11 22:33 UTC, sujaypatil96 commented
Converting this PR to draft.

Reason: Passing explicit `version` and `cmdclass` options to `setup()` in setup.py without [pbr](https://github.com/openstack/pbr) will cause the application to break. So we need to explore alternative options of implementing this. See this SO [post](https://stackoverflow.com/questions/55921981/how-can-i-use-pbr-version-from-source).

2022-05-20 16:38 UTC, sierra-moxon commented
Hi @rosdyana - we just migrated LinkML to use the poetry virtual environment and package management framework.  I think I need to close this PR as it changes files that were removed during this migration.  With that change, have we addressed your versioning concerns?  If not, please do submit another PR and we can address it ASAP.

2022-05-20 16:38 UTC, closed without merging