docs(inlining): corrected sentence
linkml/linkml pull request #513
Opened 2021-12-12 21:22 UTC by noelmcloughlin

2021-12-14 22:41 UTC, cmungall requested changes
thanks! but unfortunately the changes need to be made in the source top level `sphinx` folder.. we probably shouldn't be checking in the md.txt

2021-12-15 00:22 UTC, noelmcloughlin commented
Thanks, I'll have a look and fix up the PR.

2021-12-16 21:35 UTC, noelmcloughlin commented
PR updated.

2021-12-16 22:50 UTC, cmungall approved these changes

2021-12-16 22:50 UTC, merged