PV mappings ok with linkml-runtime 1.2.11rc1
linkml/linkml pull request #758
Opened 2022-05-09 18:48 UTC by turbomam

issue #756 

see
- tests/test_issues/test_issue_756.py
- tests/test_issues/input/issue_756.yaml

2022-05-09 18:50 UTC, turbomam commented
I have no idea why tests/test_issues/test_linkml_issue_571.py is considered a new file in this PR.

2022-05-10 00:03 UTC, cmungall commented on pyproject.toml
> +#linkml-runtime = "==1.2.*,>=1.2.4"
no need to comment out a line. git remembers everything

2022-05-10 00:03 UTC, cmungall requested changes

2022-05-10 00:03 UTC, cmungall commented on pyproject.toml
> +linkml-runtime = "==1.2.12"
>=

2022-05-10 00:17 UTC, merged