Add `term_id` argument which you can use in gen-doc jinja templates
linkml/linkml pull request #792
Opened 2022-05-18 13:14 UTC by sujaypatil96

This PR seeks to resolve issue #791.

The way in which you can enforce the usage of term_ids in URLs is by setting `term_id=True`.

2022-05-18 15:01 UTC, cmungall requested changes
Logic is good, but "term" isn't a term in linkml, instead call the parameter `use_slot_uris`

2022-05-18 15:02 UTC, cmungall commented
This also leaves open to use_class_uris in future (not a MIxS reqt yet?)

2022-05-19 06:47 UTC, sujaypatil96 commented
Hm, yes, that's true. It does let us extrapolate the same functionality to be applicable to classes by exposing a use_class_uris argument. But it isn't a MIxS requirement just yet.

2022-05-19 16:36 UTC, cmungall commented on linkml/generators/docgen.py
> +            n = self.name(s, use_slot_uris=self.use_slot_uris)
the logic here is odd. use_slot_uris is already an instance attribute on the Generator

2022-05-19 16:48 UTC, cmungall approved these changes

2022-05-19 17:10 UTC, merged