own, inherited and mixed attributes functionality in docgen
linkml/linkml pull request #888
Opened 2022-07-29 21:25 UTC by sujaypatil96

This PR addresses issue #878

2022-08-09 16:18 UTC, cmungall commented on linkml/generators/docgen.py
> +
remove blank lines

2022-08-09 16:19 UTC, cmungall commented on tests/test_generators/input/kitchen_sink.yaml
> +    domain_of: Person
remove these. These are not asserted

2022-08-09 16:20 UTC, cmungall requested changes
for this to be useful, it shouldn't rely on domain_of being asserted

2022-08-25 23:02 UTC, sujaypatil96 commented
So we need to write logic that computes all classes that are in the domain of a slot without the explicit assertion of domain_of?

2022-09-15 15:22 UTC, cmungall commented on linkml/generators/docgen.py
> +    def fetch_own_attributes_of_class(self, cls: ClassDefinition) -> List[SlotDefinitionName]:
call this `get_direct_slots`

2022-09-15 15:22 UTC, cmungall commented on linkml/generators/docgen.py
> +    def fetch_inherited_attributes_of_class(self, cls: ClassDefinition) -> List[SlotDefinitionName]:
call this `get_indirect_slots`

2022-09-15 15:23 UTC, cmungall commented on linkml/generators/docgen.py
> +    def fetch_mixed_in_slots_of_class(self, cls: ClassDefinition) -> Dict[str, List[str]]:
call this `get_mixin_inherited_slots`

2022-09-15 22:16 UTC, merged